<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>O Começo do Fim</title>
    <style>
        body {
            background-color: black;
            color: white;
            font-family: Arial, sans-serif;
            text-align: center;
            margin-top: 20%;
        }

        h1 {
            font-size: 3em;
            margin-bottom: 20px;
        }

        #timer {
            color: red;
            font-size: 4em;
        }
    </style>
</head>
<body>
    <h1>O começo do fim</h1>
    <div id="timer">24:00:00</div>

    <script>
        // Definindo o tempo inicial em segundos (24 horas = 86400 segundos)
        var totalTime = 24 * 60 * 60;

        function startTimer() {
            var timerElement = document.getElementById('timer');
            
            // Função que atualiza o timer a cada segundo
            var countdown = setInterval(function() {
                // Calcula horas, minutos e segundos restantes
                var hours = Math.floor(totalTime / 3600);
                var minutes = Math.floor((totalTime % 3600) / 60);
                var seconds = Math.floor(totalTime % 60);

                // Formata o timer no formato HH:MM:SS
                timerElement.innerHTML = 
                    (hours < 10 ? '0' + hours : hours) + ':' +
                    (minutes < 10 ? '0' + minutes : minutes) + ':' +
                    (seconds < 10 ? '0' + seconds : seconds);

                // Diminui o tempo total em 1 segundo
                totalTime--;

                // Para o timer quando chega a 0
                if (totalTime < 0) {
                    clearInterval(countdown);
                    timerElement.innerHTML = "00:00:00";
                }
            }, 1000);
        }

        // Inicia o timer ao carregar a página
        startTimer();
    </script>
</body>
</html>

          echo Add other actions to build,
          echo test, and deploy your project.
